[
 {
  "hosts":[
   "vip.lz",
   "hd.lz",
   "v.cdnlz",
   "vip.ffzy",
   "hd.ffzy",
   "cdn-vipvideo",
   "nbfjhertyrxiang",
   "sekihfde",
   "super.ffzy",
   "fhbbff",
   "vvip"
  ],
  "name":"量非",
  "regex":[
   "25.1",
   "18.266",
   "18.5333",
   "23.466666",
   "17.99",
   "14.45",
   "17.19",
   "#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*?11697777.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*?p1ayer.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*?1171(057).*?\\.ts",
   "#EXTINF.*?\\s+.*?6d7b(077).*?\\.ts",
   "#EXTINF.*?\\s+.*?6718a(403).*?\\.ts",
   "#EXTINF.*?\\s+.*?adjump.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*a241.*?\\.ts\\s+",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:6.600000,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*?11697777.*?\\.ts\\s+",
   "#EXTINF.*?\\s+.*?p1ayer.*?\\.ts\\s+",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:7\\.166667,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:4\\.066667,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:6\\.400000,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:1\\.28,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXTINF.*?\\s+.*?1171(057).*?\\.ts",
   "#EXTINF.*?\\s+.*?6d7b(077).*?\\.ts",
   "#EXTINF.*?\\s+.*?6718a(403).*?\\.ts",
   "#EXT-X-PLAYLIST-TYPE:VOD\\r*\\n*#EXTINF:5\\.600000,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 },
 {
  "hosts":[
   "haiwaikan"
  ],
  "name":"海外看",
  "regex":[
   "8.16",
   "8.1748",
   "10.0099",
   "10.3333",
   "10.85",
   "12.33",
   "16.0599",
   "10.0099"
  ]
 },
 {
  "hosts":[
   "suonizy"
  ],
  "name":"索尼",
  "regex":[
   "15.1666",
   "15.2666",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:7\\680000,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"
  ]
 },
 {
  "hosts":[
   "bfengbf.com",
   "bfzy",
   "ddbbffcdn",
   "rrcdnbf",
   "bbffvip",
   "7bbffvip",
   "bvvvvvvv7f"
  ],
  "name":"暴風",
  "regex":[
   "#EXTINF.*?\\s+.*?adjump.*?\\.ts\\s+",
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"
  ]
 },
 {
  "hosts":[
   "lsbbf2",
   "97img",
   "vvip",
   ".vip",
   "thm3u8",
   "vostrely",
   "askzybf"
  ],
  "name":"去你的广告",
  "regex":[
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY",
  "#EXTINF:5,[\\s\\S]*?#EXT-X-DISCONTINUITY"
   ]
 },

  {
  "hosts":[
   "aws.ulivetv.net"
  ],
  "name":"星星",
  "regex":[
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 },
   {
  "hosts":[
   "ryplay",
   "sysybf"
  ],
  "name":"猎手短剧",
  "regex":[
   "#EXT-X-DISCONTINUITY\r*\n*#EXTINF:5.680000,[\\s\\S]*?#EXT-X-DISCONTINUITY",
    "#EXTINF:4.4,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 },
  {
  "hosts":[
   "fqm3u8"
  ],
  "name":"fq去插",
  "regex":[
   "#EXT-X-KEY:METHOD=AES-128[\\s\\S]*?#EXTINF:3[\\s\\S]*GcS4RzMZ[\\s\\S]*?#EXT-X-DISCONTINUITY"
   
  ]
  

 },
   {
  "hosts":[
   "55p"
  ],
  "name":"55p去插",
  "regex":[
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:4.4,[\\s\\S]*?#EXT-X-DISCONTINUITY"
   
  ]
  

 },
 {
  "hosts":[
   "askzycdn",
   "jkunbf",
   "bfikuncdn",
   "ddcdnbf",
   "bfaskcdn"
  ],
  "name":"开源棋牌",
  "regex":[
   "#EXTINF.*?\\s+.*?aaaa.*?\\.ts\\s+",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:5,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=AES-128,URI=\"[^\"]+\"\r*\n*#EXTINF:3\\.333,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:5,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:2\\.4,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:1\\.467,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 },
 {
  "hosts":[
   "nbfjhertyrxiang"
  ],
  "name":"LBW",
  "regex":[
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:2\\.4,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:1\\.467,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 },
  {
  "hosts":[
   "kuaikan"
  ],
  "name":"快看",
  "regex":[
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:5,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:2\\.4,[\\s\\S]*?#EXT-X-DISCONTINUITY",
   "#EXT-X-KEY:METHOD=NONE\r*\n*#EXTINF:1\\.467,[\\s\\S]*?#EXT-X-DISCONTINUITY"
  ]
 }
]